# Rakefile for cabar/example components.

task :default => :doc_graphs

desc "generates dependency graphs under doc/"
task :doc_graphs do
  [ [ ], [ :show_facet_names ], [ :show_unrequired_components ], [ :show_unrequired_components, :group_component_versions ] ].each do | opts | 
    opts_fn = opts.map{|o| x = [ ]; o.to_s.scan(/(^|_)([a-z])/i){|m| x << $2}; x.join('')}
    base_file = "doc/#{([ :cabar ] + opts_fn).join('.')}"
    dot_file = "#{base_file}.dot"

    sh "bin/cbr_env cbr comp dot --show-dependencies #{opts.map{|o| "--#{o}"}.join(' ')} > #{dot_file}"

    # [ :dot, :neato, :twopi, :circo, :fdp ].
    [ :dot, :neato ].
      each do | g |
      sh "#{g} -Tsvg -o #{dot_file}.#{g}.svg #{dot_file}"
    end
  end
end

task :clean do
  sh "rm -f doc/*.dot doc/*.svg"
end

